## 作業三

### 方法一

In [ ]:
! wget https://raw.githubusercontent.com/ywchiu/tibame_tm/master/data/creditcard_titles.csv

--2020-07-29 11:32:37--  https://raw.githubusercontent.com/ywchiu/tibame_tm/master/data/creditcard_titles.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3688 (3.6K) [text/plain]
Saving to: ‘creditcard_titles.csv’

creditcard_titles.c 100%[===================>]   3.60K  --.-KB/s    in 0s      

2020-07-29 11:32:37 (60.6 MB/s) - ‘creditcard_titles.csv’ saved [3688/3688]



In [ ]:
titles = []
with open('creditcard_titles.csv') as f:
  for line in f.readlines()[1:]:
    titles.append(line.strip().split(',')[1])

In [ ]:
#titles

### 方法二

In [ ]:
import pandas
df = pandas.read_csv('creditcard_titles.csv', index_col = 0)

In [ ]:
titles = df['title'].tolist()

### 方法三

In [ ]:
import pandas
df = pandas.read_csv('https://raw.githubusercontent.com/ywchiu/tibame_tm/master/data/creditcard_titles.csv', index_col = 0)

In [ ]:
titles = df['title'].tolist()

In [ ]:
import jieba
jieba.add_word('台新')
jieba.add_word('富邦')
jieba.load_userdict('userdict.txt')
corpus = []
for title in titles:
  corpus.append(' '.join(jieba.cut(title)))
#print(corpus)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words = ['不是'])
X = vectorizer.fit_transform(corpus)

In [ ]:
print(vectorizer.get_feature_names())

['10', '109', '15', '150', '18', '2020', '50', 'ana', 'app', 'apple', 'bear', 'costco', 'gogo', 'happy', 'hello', 'icash', 'kitty', 'line', 'linepay', 'money', 'money101', 'only', 'pay', 'pi', 're', 'ubear', 'ubereat', 'wallet', 'youbike2', '三代', '三倍', '三越', '上市', '上網', '上路', '下半年', '不划算', '世界', '中信', '中油', '付款', '位券', '使用', '促刷', '信用卡', '倍券', '優惠', '元大', '兆豐', '全新', '凱基', '分期', '分眾', '列入', '刷卡', '券綁', '加碼', '助理', '匯豐', '匯豐及', '卡娜', '卡換', '卡新戶禮', '卡會', '卡未核', '卡申', '卡莉', '卡面', '可以', '台哥', '台新', '合庫', '名額', '售票', '商務御璽', '商機', '問去', '問題', '嘟嘟', '回饋', '國旅', '國泰', '園學費', '土地', '城市', '外幣', '多家', '大滿', '大聯名', '太陽', '如何', '學貸', '家人', '寄來', '富邦', '寰宇', '小白', '屈臣氏', '年繳', '幼兒', '張高', '影城', '御璽', '心得', '悍將', '悠遊', '情報', '感謝', '應援哩', '懶人包', '房停車', '折抵', '抽獎', '拚振興', '指定', '振新券', '振興券', '掛號', '推數', '推薦', '推銷', '改換', '整理', '新光', '新戶', '新聞', '星展', '最新', '有人', '未過', '本月', '查詢', '核卡', '樂天', '樂跑', '正常', '永豐幣', '沒有', '活動', '消費', '渣打', '炫晶', '無限卡享', '熊回饋', '燃料', '玉山', '現金', '申請', '疑問', '研究', '神奇', '算實體'

In [ ]:
X

<71x198 sparse matrix of type '<class 'numpy.int64'>'
	with 451 stored elements in Compressed Sparse Row format>

In [ ]:
import re
corpus = []
for title in titles:
  segwords = []
  for word in jieba.cut(title):
    m = re.match('[\u4e00-\u9fa5]+', word)
    if m:
      segwords.append(word)
  corpus.append(' '.join(segwords))

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [ ]:
print(vectorizer.get_feature_names())

['三代', '三倍', '三越', '上市', '上網', '上路', '下半年', '不划算', '不是', '世界', '中信', '中油', '付款', '位券', '使用', '促刷', '信用卡', '倍券', '優惠', '元大', '兆豐', '全新', '凱基', '分期', '分眾', '列入', '刷卡', '券綁', '加碼', '助理', '匯豐', '匯豐及', '卡娜', '卡換', '卡新戶禮', '卡會', '卡未核', '卡申', '卡莉', '卡面', '可以', '台哥', '台新', '合庫', '名額', '售票', '商務御璽', '商機', '問去', '問題', '嘟嘟', '回饋', '國旅', '國泰', '園學費', '土地', '城市', '外幣', '多家', '大滿', '大聯名', '太陽', '如何', '學貸', '家人', '寄來', '富邦', '寰宇', '小白', '屈臣氏', '年繳', '幼兒', '張高', '影城', '御璽', '心得', '悍將', '悠遊', '情報', '感謝', '應援哩', '懶人包', '房停車', '折抵', '抽獎', '拚振興', '指定', '振新券', '振興券', '掛號', '推數', '推薦', '推銷', '改換', '整理', '新光', '新戶', '新聞', '星展', '最新', '有人', '未過', '本月', '查詢', '核卡', '樂天', '樂跑', '正常', '永豐幣', '沒有', '活動', '消費', '渣打', '炫晶', '無限卡享', '熊回饋', '燃料', '玉山', '現金', '申請', '疑問', '研究', '神奇', '算實體', '簡訊', '粉紅', '紙本', '紙本券', '經濟部', '線上', '繳卡費', '繳稅', '繳納', '繳費', '聯名', '聯邦', '聯邦卡', '自動', '花旗', '討論', '調額', '請問', '謄本', '證明', '財力', '貫之路', '費用', '賴點', '近視', '這是', '通路', '金卡', '金融', '金袋', '金額', '銀行', '鑽金', '閒聊', '關於', '限制', '雷射', '電話',

In [ ]:
import re
corpus = []
for title in titles:
  corpus.append([word for word in jieba.cut(title) if re.match('[\u4e00-\u9fa5]+', word)])
  

In [ ]:
class ChineseCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(ChineseCountVectorizer, self).build_analyzer()
        return lambda doc: (w for w in analyzer(doc) if re.match('[\u4e00-\u9fa5]+', w))

In [ ]:
corpus = []
for title in titles:
  corpus.append(' '.join(jieba.cut(title)))

In [ ]:
vectorizer = ChineseCountVectorizer()
X = vectorizer.fit_transform(corpus)

In [ ]:
print(vectorizer.get_feature_names())

['三代', '三倍', '三越', '上市', '上網', '上路', '下半年', '不划算', '不是', '世界', '中信', '中油', '付款', '位券', '使用', '促刷', '信用卡', '倍券', '優惠', '元大', '兆豐', '全新', '凱基', '分期', '分眾', '列入', '刷卡', '券綁', '加碼', '助理', '匯豐', '匯豐及', '卡娜', '卡換', '卡新戶禮', '卡會', '卡未核', '卡申', '卡莉', '卡面', '可以', '台哥', '台新', '合庫', '名額', '售票', '商務御璽', '商機', '問去', '問題', '嘟嘟', '回饋', '國旅', '國泰', '園學費', '土地', '城市', '外幣', '多家', '大滿', '大聯名', '太陽', '如何', '學貸', '家人', '寄來', '富邦', '寰宇', '小白', '屈臣氏', '年繳', '幼兒', '張高', '影城', '御璽', '心得', '悍將', '悠遊', '情報', '感謝', '應援哩', '懶人包', '房停車', '折抵', '抽獎', '拚振興', '指定', '振新券', '振興券', '掛號', '推數', '推薦', '推銷', '改換', '整理', '新光', '新戶', '新聞', '星展', '最新', '有人', '未過', '本月', '查詢', '核卡', '樂天', '樂跑', '正常', '永豐幣', '沒有', '活動', '消費', '渣打', '炫晶', '無限卡享', '熊回饋', '燃料', '玉山', '現金', '申請', '疑問', '研究', '神奇', '算實體', '簡訊', '粉紅', '紙本', '紙本券', '經濟部', '線上', '繳卡費', '繳稅', '繳納', '繳費', '聯名', '聯邦', '聯邦卡', '自動', '花旗', '討論', '調額', '請問', '謄本', '證明', '財力', '貫之路', '費用', '賴點', '近視', '這是', '通路', '金卡', '金融', '金袋', '金額', '銀行', '鑽金', '閒聊', '關於', '限制', '雷射', '電話',

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

## Euclidean Distance

In [ ]:
contents = ['This is a toy post about machine learning. Actually, it contains not much interesting stuff.',
'Imaging databases can get huge.',
'Most imaging databases safe images permanently.',
'Imaging databases store images.',
'Imaging databases store images. Imaging databases store images. Imaging databases store images.']

In [ ]:
corpus = []
for doc in contents:
  corpus.append(doc.lower())

In [ ]:
corpus = [doc.lower() for doc in contents]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [ ]:
X

<5x24 sparse matrix of type '<class 'numpy.int64'>'
	with 33 stored elements in Compressed Sparse Row format>

In [ ]:
X[0].toarray().flatten()

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1])

In [ ]:
X[1].toarray().flatten()

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [ ]:
import math
math.sqrt(sum((X[0].toarray().flatten() - X[1].toarray().flatten()) ** 2))

4.358898943540674

In [ ]:
import scipy as sp

def dist_raw(v1, v2):
  delta = v1-v2
  return sp.linalg.norm(delta.toarray())


In [ ]:
dist_raw(X[0] ,X[1] )

4.358898943540674

In [ ]:
from sklearn.metrics.pairwise import euclidean_distances
euclidean_distances(X)

array([[0.        , 4.35889894, 4.47213595, 4.24264069, 7.07106781],
       [4.35889894, 0.        , 2.64575131, 2.23606798, 5.38516481],
       [4.47213595, 2.64575131, 0.        , 2.        , 4.89897949],
       [4.24264069, 2.23606798, 2.        , 0.        , 4.        ],
       [7.07106781, 5.38516481, 4.89897949, 4.        , 0.        ]])

## Jaccard Similarity

In [ ]:
import numpy as np
a = np.array([3,3,1,0,0,2])
(a > 0).astype(int)

array([1, 1, 1, 0, 0, 1])

In [ ]:
np.asarray(a, np.bool)

array([ True,  True,  True, False, False,  True])

In [ ]:
def jaccard(v1,v2):
  v1 = np.asarray(v1, np.bool)
  v2 = np.asarray(v2, np.bool)
  return np.double(np.bitwise_and(v1, v2).sum()) / np.double(np.bitwise_or(v1, v2).sum())

In [ ]:
jaccard(X[0].toarray().flatten(),X[1].toarray().flatten())

0.0

In [ ]:
jaccard(X[3].toarray().flatten(),X[4].toarray().flatten())

1.0

In [ ]:
from sklearn.metrics import jaccard_score
v1 = np.asarray(X[3].toarray().flatten(), np.bool)
v2 = np.asarray(X[4].toarray().flatten(), np.bool)
jaccard_score(v1, v2)

1.0

In [ ]:
X.shape

(5, 24)

In [ ]:
X.shape[0]

5

In [ ]:
n = X.shape[0]

In [ ]:
m = np.zeros((n,n))
m

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
for i in range(n):
  for j in range(n):
    v1 = np.asarray(X[i].toarray().flatten(), np.bool)
    v2 = np.asarray(X[j].toarray().flatten(), np.bool)
    m[i,j] = jaccard_score(v1, v2)

In [ ]:
m

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.22222222, 0.28571429, 0.28571429],
       [0.        , 0.22222222, 1.        , 0.42857143, 0.42857143],
       [0.        , 0.28571429, 0.42857143, 1.        , 1.        ],
       [0.        , 0.28571429, 0.42857143, 1.        , 1.        ]])

## Cosine Slimilarity

In [ ]:
import math
def cos_similarity(v1,v2):
  return np.dot(v1,v2) / math.sqrt((v1 ** 2).sum()) * math.sqrt((v2 ** 2).sum())

In [ ]:
cos_similarity(X[0].toarray().flatten(),X[1].toarray().flatten())

0.0

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(X)

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.36514837, 0.4472136 , 0.4472136 ],
       [0.        , 0.36514837, 1.        , 0.61237244, 0.61237244],
       [0.        , 0.4472136 , 0.61237244, 1.        , 1.        ],
       [0.        , 0.4472136 , 0.61237244, 1.        , 1.        ]])

In [ ]:
from sklearn.metrics.pairwise import cosine_distances
cosine_distances(X)

array([[0.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 0.        , 0.63485163, 0.5527864 , 0.5527864 ],
       [1.        , 0.63485163, 0.        , 0.38762756, 0.38762756],
       [1.        , 0.5527864 , 0.38762756, 0.        , 0.        ],
       [1.        , 0.5527864 , 0.38762756, 0.        , 0.        ]])

In [ ]:
# distance = 1 - similarity
# similarity = 1 - distance

## TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)


In [ ]:
X

<5x24 sparse matrix of type '<class 'numpy.float64'>'
	with 33 stored elements in Compressed Sparse Row format>

In [ ]:
X.toarray()

array([[0.26726124, 0.26726124, 0.        , 0.26726124, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.26726124,
        0.26726124, 0.26726124, 0.26726124, 0.26726124, 0.        ,
        0.26726124, 0.26726124, 0.        , 0.26726124, 0.        ,
        0.        , 0.26726124, 0.26726124, 0.26726124],
       [0.        , 0.        , 0.52451722, 0.        , 0.29550385,
        0.52451722, 0.52451722, 0.        , 0.29550385, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.27880274,
        0.        , 0.        , 0.33142212, 0.27880274, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.49487286,
        0.        , 0.        , 0.49487286, 0.        , 0.49487286,
        0.        , 0.        , 0.        , 0.        ],
       [0.   

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(X)

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.16477457, 0.25283852, 0.25283852],
       [0.        , 0.16477457, 1.        , 0.40709381, 0.40709381],
       [0.        , 0.25283852, 0.40709381, 1.        , 1.        ],
       [0.        , 0.25283852, 0.40709381, 1.        , 1.        ]])

## 蝦皮爬蟲

In [ ]:
import requests
headers = {
  'referer': 'https://shopee.tw/%E7%AD%86%E8%A8%98%E5%9E%8B%E9%9B%BB%E8%85%A6-cat.69.2156?page=3',  
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36'  
}
res = requests.get('https://shopee.tw/api/v2/search_items/?by=relevancy&fe_categoryids=2156&limit=50&newest=150&order=desc&page_type=search&version=2', headers = headers)
jd = res.json()

In [ ]:
for item in jd['items']:
  print(item.get('name'))

全新未拆 MacBook Air 128G
Apple MacBook Pro 13.3吋 1.4GHZ/8GB/128GB Touch Bar 灰/銀
ASUS 華碩 TUF FX505 FX505DV-0081B3750H 15吋 薄邊 電競 筆電 黑
2020版 MacBook Pro 13吋 16G / 512GB 全新未拆封 TouchBar 台灣公司貨
ACER 宏碁 Swift 3 SF314 58 5720 i5-10210U 1TB 粉 14吋 輕薄筆電
(讓您把Macbook換下來的SSD一秒變成NVME M.2給PC使用!!)蘋果原廠SSD轉桌電用M.2 NGFF轉接卡
華碩 ASUS X550DP X550EA X550J X550JX X550L X550VC 筆電鍵盤 按鍵
ASUS 華碩 E203 E203MA 粉/白【11.6吋/Buy3c奇展】蝦皮嚴選
超輕薄》免運Fujitsu U772輕薄遊戲繪圖筆記型電腦 i5三代/4G/500G+24G SSD可升8G升固態
~熊俗3C~ ASUS 華碩 X407MA-0021DN4100 玫瑰金(熊俗~有店面) X407MA X407
筆記型電腦 華碩-聯想-宏基-dell -聯想 筆電 大理石花岗岩保護膜 貼膜
聯想 Lenovo IdeaPad 320 15IKB 81BG00LNTW 筆記型電腦 鈦灰 i7-8550U 拆封品
ACER 宏碁 Swift 3 SF314 58G 52AL i5-10210U  MX250 粉 14吋 輕薄筆電
│秒殺價│戴爾 DELL XPS 8500 1155 主板 H77 DH77M01 CY0629 0YJT1
全新 刀鋒 14寸 四核 超薄極速 可遊戲 打lol 英雄聯盟 戰勝  asus   筆記型電腦
【24出貨】蘋果電腦電池 型號 A1369 A1466 2013 2014 2015年款MacBook Air 13吋
APPLE MacBook Pro TB系列 i7/16G/512G/銀/灰 16吋筆電
網路教學/遠端教學/在家上課用大筆電 wifi ok/ 光碟 ok / 上網 ok /看電影 ok
【當天出貨】蘋果電腦喇叭 型號A1398  2013 2014 2015年MacBook Pro Retina 15吋
華碩 ASUS

## 建立推薦系統

In [ ]:
import pandas
df = pandas.read_csv('https://raw.githubusercontent.com/ywchiu/tibame_tm/master/data/shopee_laptop.csv', index_col = 0)

In [ ]:
len(df)

247

In [ ]:
for idx, product in df.iterrows():
  print(idx, product.get('name'))
  break

0 APPLE MacBook Air系列 i3 雙核心/8G/256G/銀/金/灰 13吋筆電 2020新機 【現貨】


In [ ]:
import jieba
corpus = []
titles = []
for idx, product in df.iterrows():
  corpus.append(' '.join(jieba.cut(product.get('name'))))
  titles.append(product.get('name'))

In [ ]:
corpus[0]

'APPLE   MacBook   Air 系列   i3   雙 核心 / 8G / 256G / 銀 / 金 / 灰   13 吋 筆電   2020 新機   【 現貨 】'

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

In [ ]:
X

<247x992 sparse matrix of type '<class 'numpy.float64'>'
	with 2844 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.metrics.pairwise import cosine_distances
cs = cosine_distances(X)

In [ ]:
cs[0].shape

(247,)

In [ ]:
cs[0].argsort()[1:6]

array([ 84, 134,  70, 124,   1])

In [ ]:
titles[0]

'APPLE MacBook Air系列 i3 雙核心/8G/256G/銀/金/灰 13吋筆電 2020新機 【現貨】'

In [ ]:
for idx in cs[0].argsort()[1:6]:
  print(titles[idx])

APPLE MacBook Air系列 i5 四核心/8G/512G/銀/金/灰 13吋筆電 2020新機 【現貨】
APPLE MacBook Pro系列 2020新機(i5 四核心/8G/256G/太空灰/銀色) 13吋蘋果筆電
APPLE MacBook Air系列 i5/8G/256G/銀/金/灰 13吋筆電 2019年版 【現貨】
Apple MacBook Air 13.3/1.1/8G/256G/金/銀/灰 2020新款
APPLE MacBook Air系列 i5/8G/128G/銀/金/灰 13吋筆電 2019年版 【現貨】


In [ ]:
def getRecommendation(productid):
  print('[閱覽商品]:',titles[productid])
  cs = cosine_distances(X[productid], X).flatten()
  for idx in cs.argsort():
    if cs[idx] < 0.5:
      print('[推薦商品]:',titles[idx], cs[idx])


getRecommendation(1)

[閱覽商品]: APPLE MacBook Air系列 i5/8G/128G/銀/金/灰 13吋筆電 2019年版 【現貨】
[推薦商品]: APPLE MacBook Air系列 i5/8G/128G/銀/金/灰 13吋筆電 2019年版 【現貨】 0.0
[推薦商品]: APPLE MacBook Air系列 i5/8G/256G/銀/金/灰 13吋筆電 2019年版 【現貨】 0.09117817352695867
[推薦商品]: APPLE MacBook Air系列 i5 四核心/8G/512G/銀/金/灰 13吋筆電 2020新機 【現貨】 0.4330531881144122
[推薦商品]: APPLE MacBook Air系列 i3 雙核心/8G/256G/銀/金/灰 13吋筆電 2020新機 【現貨】 0.49139807168791905


## 新聞推薦系統

In [ ]:
import pandas
news = pandas.read_excel('https://raw.githubusercontent.com/ywchiu/tibame_tm/master/data/news.xlsx', index_col = 0)

In [ ]:
news.head()

category  ...                           title
0       政治  ...  【更新】水利會改官派明闖關　綠委24小時前顧議場大門防藍突襲
1       論壇  ...               請中市府為所當為 加速中火燃煤限制
2       社會  ...              陸生共諜嗆台司法　「不敢公開審理我」
3       生活  ...             【特企】NGO聯名譴責中共迫害宗教信仰
4       生活  ...       乘客搭大客車不配合繫安全帶　立院初審通過可罰6千元

[5 rows x 4 columns]

In [ ]:
corpus = []
titles = []
for idx, article in news.iterrows():
  corpus.append(' '.join(jieba.cut(article.get('content'))))
  titles.append(article.get('title'))

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

In [ ]:
X

<899x38651 sparse matrix of type '<class 'numpy.float64'>'
	with 128155 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.metrics.pairwise import cosine_distances
def getSimiliarArticle(articleid):
  print('[查詢文章]:',titles[articleid])
  cs = cosine_distances(X[articleid], X).flatten()
  related_index = cs.argsort()[1:]
  for idx in related_index:
    if cs[idx] < 0.88:
      print('[相關文章]:',titles[idx], cs[idx])


getSimiliarArticle(5)

[查詢文章]: Fed升息美元走軟　台幣今再升破30元大關
[相關文章]: 靜候FOMC結論　台幣平盤整理午盤小貶0.5分 0.6655307049153734
[相關文章]: 川普不給力美元軟趴趴　歐元料再升逾10% 0.6969043056696386
[相關文章]: 【Fed有鴿味】美元軟了黃金硬了　美股道指創新高 0.7042793123333844
[相關文章]: Fed升息符合預期　經濟學家：大家可過個平安聖誕節 0.7255010959627639
[相關文章]: Fed宣布升息1碼　台股早盤大漲逾百點 0.7327284108063947
[相關文章]: 強總裁、弱台灣　央行年繳1800億造成4大後遺症 0.7934789647726109
[相關文章]: 蘋果寫傳奇！上市37周年股價飆436倍 0.8569814959531834
[相關文章]: 北韓高仿假鈔流入南韓　專家驚：近乎完美 0.8639965877163968
[相關文章]: 【Fed告別秀】葉倫談比特幣　以7個字總結 0.8727242116759012
[相關文章]: 十二月十三日財經焦點搶先看 0.8783137137921018


###Practice

In [21]:
import pandas as pd
import jieba
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_distances
df = pd.read_excel("https://raw.githubusercontent.com/ywchiu/tibame_tm/master/data/news.xlsx", index_col = 0)

# word cutting
corpus = []
titles = []
for idx, item in df.iterrows():
  corpus.append(" ".join(jieba.lcut(item.get('content'))))
  titles.append(item.get('title'))
# print(corpus)
# print(titles)


In [23]:
# word vectorizing
t_vectorizer = TfidfVectorizer()
corpus_vec = t_vectorizer.fit_transform(corpus)


# recommend function
def recommend(id):
  c_dist = cosine_distances(corpus_vec[id],corpus_vec).flatten()
  for id in c_dist.argsort()[1:6]:
    print("recommend article title: ", titles[id], c_dist[id])

# testing
reading_title_id = 35
print("reading_title: ", titles[reading_title_id])
recommend(reading_title_id)

reading_title:  FBI探員罵川普「白痴」　遭調離通俄門調查
recommend article title:  【公道難伸張】再控川普性騷　受害者：沒人在乎很受傷 0.8811793632509274
recommend article title:  老謝：美菲2位狂人兄弟 今年交出不錯成績單　 0.8902177482789575
recommend article title:  【滑鐵盧片】川普大挫敗！　共和黨在鐵票倉阿拉巴馬州敗北 0.927949241178453
recommend article title:  阿拉巴馬州變天　起訴3K黨檢察官勝仇同法官 0.9298769573988401
recommend article title:  瓊斯獲勝！又逢結婚紀念日　王丹：川普連任路荊棘 0.9315696830117044


### Vectorizer

- fit:產生結構
- transform:轉換資料
- fit_transform: 產生結構並轉換資料

In [ ]:
query = '罷免黃國昌'
query_corpus = [' '.join(jieba.cut(query))]
query_corpus

['罷免 黃 國昌']

In [ ]:
query_vec = vectorizer.transform(query_corpus)

In [ ]:
cs = cosine_distances(query_vec, X).flatten()

In [ ]:
a = np.array([[1,2,3,4,5]])
a.flatten()

array([1, 2, 3, 4, 5])

In [ ]:
for idx in cs.argsort()[0:5]:
  #print(idx)
  print(titles[idx])

黃國昌若被罷免會更強　他：成為選輸北市的阿扁
宗教團體可曾想過：黃國昌犀利形象恐越打越旺
罷昌案周六投票　時代力量全力澄清不實謠言
【聲援片】沈發惠呼籲罷昌案投「不同意」　黃國昌：謝謝您
罷免案將投票　李遠哲今再度現身力挺黃國昌


In [ ]:
for idx in cs.argsort():
  if cs[idx] < 0.8:
    print(titles[idx], cs[idx])

黃國昌若被罷免會更強　他：成為選輸北市的阿扁 0.5816699773794642
宗教團體可曾想過：黃國昌犀利形象恐越打越旺 0.6252315673987536
罷昌案周六投票　時代力量全力澄清不實謠言 0.6528815421955868
【聲援片】沈發惠呼籲罷昌案投「不同意」　黃國昌：謝謝您 0.6648825647690275
罷免案將投票　李遠哲今再度現身力挺黃國昌 0.7095793102576216
黃國昌：長期目標要消滅國民黨　不支持柯文哲的兩岸一家親 0.7501304150696924
【慶富案】黃國昌再咬高雄銀　協助慶富不實增資 0.7919287976065514


In [ ]:
def getQuerySimiliarArticle(query):
  query_corpus = [' '.join(jieba.cut(query))]
  query_vec = vectorizer.transform(query_corpus)
  cs = cosine_distances(query_vec, X).flatten()
  for idx in cs.argsort():
    if cs[idx] < 0.8:
      print(titles[idx], cs[idx])

In [ ]:
getQuerySimiliarArticle('小嫻跟許聖梅')

「小嫻不快樂！」　許聖梅：何守正虧欠她 0.6065969437090841
許聖梅心疼小嫻被當空氣　爆何守正「有兩個女學員」 0.6661956436084142
【內幕動畫】小嫻婚變何守正姊反擊　不滿媽煮飯侍奉星媳婦 0.7213274731949755
【獨家內幕】太傷！小嫻被分手　何守正當小三面前攤牌 0.7311526242211511
【狗仔偷拍】小嫻搬離何守正家租66坪房　月租6萬元 0.7396835450700476
【獨家】小嫻賣房求子　婆婆竟拒入籍何家 0.752456315147892
小嫻信奉妙禪　關鍵原因與何守正有關！ 0.7626285590995772
【動畫解盤】毒菇跳火線譙seafood　小嫻難瘦香菇 0.7827202511222566
小嫻離婚導火線　拉何守正信妙禪 0.7840070218094053
【小嫻離婚】3大退讓人財兩失　求子花光430萬積蓄 0.7847623938675494
小嫻婚變無徵兆　男星嘆：兩人向來出雙入對 0.7943395555482495
